### PR TITLE
Ggenerate aggregated dataset for product

### PR DESCRIPTION
**Pull request by lizgzil**
---

# Description

fyi @india-kerle not sure if this really needs reviewing or merging (as I imagine we will change this + put it in a script), but just for clarity this is the notebook to create the aggregated dataset that Suraj is using

Fixes # (issue)

# Instructions for Reviewer

In order to test the code in this PR you need to ...

Please pay special attention to ...

# Checklist:

- [ ] I have refactored my code out from `notebooks/`
- [ ] I have checked the code runs
- [ ] I have tested the code
- [ ] I have run `pre-commit` and addressed any issues not automatically fixed
- [ ] I have merged any new changes from `dev`
- [ ] I have documented the code
  - [ ] Major functions have docstrings
  - [ ] Appropriate information has been added to `README`s
- [ ] I have explained this PR above
- [ ] I have requested a code review

### CODE REVIEW

**Comment by india-kerle** [comment]
thanks @lizgzil ! I can add to this PR to include some of those issues we've spoken about for suraj in anticipation of the next sprint i.e. add soc descriptions, geography etc.

**Comment by lizgzil** [comment]
> thanks @lizgzil ! I can add to this PR to include some of those issues we've spoken about for suraj in anticipation of the next sprint i.e. add soc descriptions, geography etc.

sounds good!

**Comment by india-kerle** [comment]
I've used the updated sic measures and added clean soc names, 6 digit soc descriptions, top 5 locations, median salaries to this spreadsheet in the 191023 tab: https://docs.google.com/spreadsheets/d/1vq44rnmkRXbUSIatnn0NyrCc-8gZK5ZbLjk3EykyMlY/edit#gid=68929895

**Comment by lizgzil** [comment]
fyi @india-kerle I'm closing this since it is was repeated in a more recent PR

**Pull request closed without merging**
